# Generated by Django 2.2.3 on 2019-07-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='customization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
